// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('holmesal.firesolver', ['firebase']).provider('firesolver', function() {
    var firesolver, opts;
    firesolver = function($firebase, $q, $rootScope) {
      var firebaseURL;
      firebaseURL = null;
      return {
        get: function(path, ultimatePath) {
          var deferredGet, fullPath, getRef;
          if (ultimatePath == null) {
            ultimatePath = null;
          }
          deferredGet = $q.defer();
          if (opts.firebaseURL) {
            firebaseURL = opts.firebaseURL;
          } else {
            if ($rootScope.firebaseURL) {
              firebaseURL = $rootScope.firebaseURL;
            } else {
              console.error("<firesolver> Firebase URL not set - use firesolverProvider.config() or set $rootScope.firebaseURL to do this");
            }
          }
          if (path[0] !== '/') {
            path = "/" + path;
          }
          fullPath = firebaseURL + path;
          getRef = new Firebase(fullPath);
          getRef.on('value', function(snapshot) {
            var getItem;
            getItem = snapshot.val();
            if (getItem) {
              return deferredGet.resolve(getItem);
            } else {
              return deferredGet.reject("<firesolver> No data found at " + fullPath);
            }
          }, function(err) {
            return deferredGet.reject("<firesolver> Error getting data from location " + fullPath);
          });
          return deferredGet.promise;
        }
      };
    };
    opts = {};
    return {
      config: function(configOpts) {
        return opts = configOpts;
      },
      $get: firesolver
    };
  });

}).call(this);
